#!/bin/bash

### BEGIN INIT INFO
# Provides:		ap
# Required-Start:	
# Required-Stop:	
# Should-Start:		$network
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Networking for the access point
# Description:		Networking for the access point
### END INIT INFO

ifdown --force wlan0
ifdown --force ap0
ifup ap0
ifup wlan0
